project_name: wr

builds:
  - binary: wr
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X cmd.version={{.Version}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^ci:"
      - "^chore:"
      - "^style:"
      - "^refactor:"
      - "^test:"

snapshot:
  name_template: "{{ .Version }}-snapshot"
